const { Movie } = require('../models');

const movieData = [
  {
    Actors: 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing',
    Awards: 'Won 6 Oscars. Another 52 wins & 29 nominations.',
    Director: 'George Lucas',
    Genre: 'Action, Adventure, Fantasy, Sci-Fi',
    imdbID: 'tt0076759',
    imdbRating: '',
    MetacriticRating: '90/100',
    Plot: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '25 May 1977',
    RottenTomRating: '92%',
    Runtime: '121 min',
    Title: 'Star Wars: Episode IV - A New Hope',
    Type: 'movie'
  },
  {
    Actors: 'Bill Murray, Dan Aykroyd, Sigourney Weaver, Harold Ramis',
    Awards: 'Nominated for 2 Oscars. Another 6 wins & 6 nominations.',
    Director: 'Ivan Reitman',
    Genre: 'Action, Comedy, Fantasy, Sci-Fi',
    imdbID: 'tt0087332',
    imdbRating: '',
    MetacriticRating: '71/100',
    Plot: 'Three former parapsychology professors set up shop as a unique ghost removal service.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTkxMjYyNzgwMl5BMl5BanBnXkFtZTgwMTE3MjYyMTE@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '08 Jun 1984',
    RottenTomRating: '97%',
    Runtime: '105 min',
    Title: 'Ghostbusters',
    Type: 'movie'
  },
  {
    Actors: 'Marlon Brando, Gene Hackman, Christopher Reeve, Ned Beatty',
    Awards: 'Nominated for 3 Oscars. Another 17 wins & 20 nominations.',
    Director: 'Richard Donner',
    Genre: 'Action, Adventure, Drama, Sci-Fi',
    imdbID: 'tt0078346',
    imdbRating: '7.3/10',
    MetacriticRating: '80/100',
    Plot: "An alien orphan is sent from his dying planet to Earth, where he grows up to become his adoptive home's first and greatest superhero.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BMzA0YWMwMTUtMTVhNC00NjRkLWE2ZTgtOWEzNjJhYzNiMTlkXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '15 Dec 1978',
    RottenTomRating: '94%',
    Runtime: '143 min',
    Title: 'Superman',
    Type: 'movie'
  },
  {
    Actors: 'Joseph Cotten, Dorothy Comingore, Agnes Moorehead, Ruth Warrick',
    Awards: 'Won 1 Oscar. Another 10 wins & 13 nominations.',
    Director: 'Orson Welles',
    Genre: 'Drama, Mystery',
    imdbID: 'tt0033467',
    imdbRating: '8.3/10',
    MetacriticRating: '100/100',
    Plot: "Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance; 'Rosebud'.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjBiOTYxZWItMzdiZi00NjlkLWIzZTYtYmFhZjhiMTljOTdkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '05 Sep 1941',
    RottenTomRating: '99%',
    Runtime: '119 min',
    Title: 'Citizen Kane',
    Type: 'movie'
  },
  {
    Actors: 'Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains',
    Awards: 'Won 3 Oscars. Another 6 wins & 9 nominations.',
    Director: 'Michael Curtiz',
    Genre: 'Drama, Romance, War',
    imdbID: 'tt0034583',
    imdbRating: '8.5/10',
    MetacriticRating: '100/100',
    Plot: 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '23 Jan 1943',
    RottenTomRating: '99%',
    Runtime: '102 min',
    Title: 'Casablanca',
    Type: 'movie'
  },
  {
    Actors: 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano',
    Awards: 'Won 3 Oscars. Another 28 wins & 30 nominations.',
    Director: 'Francis Ford Coppola',
    Genre: 'Crime, Drama',
    imdbID: 'tt0068646',
    imdbRating: '9.2/10',
    MetacriticRating: '100/100',
    Plot: "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '24 Mar 1972',
    RottenTomRating: '98%',
    Runtime: '175 min',
    Title: 'The Godfather',
    Type: 'movie'
  },
  {
    Actors: "Thomas Mitchell, Barbara O'Neil, Vivien Leigh, Evelyn Keyes",
    Awards: 'Won 8 Oscars. Another 12 wins & 12 nominations.',
    Director: 'Victor Fleming, George Cukor, Sam Wood',
    Genre: 'Drama, History, Romance, War',
    imdbID: 'tt0031381',
    imdbRating: '8.1/10',
    MetacriticRating: '97/100',
    Plot: 'A manipulative woman and a roguish man conduct a turbulent romance during the American Civil War and Reconstruction periods.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjUyZWZkM2UtMzYxYy00ZmQ3LWFmZTQtOGE2YjBkNjA3YWZlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '17 Jan 1940',
    RottenTomRating: '91%',
    Runtime: '238 min',
    Title: 'Gone with the Wind',
    Type: 'movie'
  },
  {
    Actors: "Peter O'Toole, Alec Guinness, Anthony Quinn, Jack Hawkins",
    Awards: 'Won 7 Oscars. Another 23 wins & 14 nominations.',
    Director: 'David Lean',
    Genre: 'Adventure, Biography, Drama, History, War',
    imdbID: 'tt0056172',
    imdbRating: '8.3/10',
    MetacriticRating: '100/100',
    Plot: 'The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYWY5ZjhjNGYtZmI2Ny00ODM0LWFkNzgtZmI1YzA2N2MxMzA0XkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '11 Dec 1962',
    RottenTomRating: '97%',
    Runtime: '228 min',
    Title: 'Lawrence of Arabia',
    Type: 'movie'
  },
  {
    Actors: 'Judy Garland, Frank Morgan, Ray Bolger, Bert Lahr',
    Awards: 'Won 2 Oscars. Another 9 wins & 16 nominations.',
    Director: 'Victor Fleming, George Cukor, Mervyn LeRoy, Norman Taurog, Richard Thorpe, King Vidor',
    Genre: 'Adventure, Family, Fantasy, Musical',
    imdbID: 'tt0032138',
    imdbRating: '8.0/10',
    MetacriticRating: '92/100',
    Plot: 'Dorothy Gale is swept away from a farm in Kansas to a magical land of Oz in a tornado and embarks on a quest with her new friends to see the Wizard who can help her return home to Kansas and help her friends as well.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNjUyMTc4MDExMV5BMl5BanBnXkFtZTgwNDg0NDIwMjE@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '25 Aug 1939',
    RottenTomRating: '98%',
    Runtime: '102 min',
    Title: 'The Wizard of Oz',
    Type: 'movie'
  },
  {
    Actors: 'Anne Bancroft, Dustin Hoffman, Katharine Ross, William Daniels',
    Awards: 'Won 1 Oscar. Another 20 wins & 21 nominations.',
    Director: 'Mike Nichols',
    Genre: 'Comedy, Drama, Romance',
    imdbID: 'tt0061722',
    imdbRating: '8.0/10',
    MetacriticRating: '83/100',
    Plot: 'A disillusioned college graduate finds himself torn between his older lover and her daughter.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTQ0ODc4MDk4Nl5BMl5BanBnXkFtZTcwMTEzNzgzNA@@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '21 Dec 1967',
    RottenTomRating: '87%',
    Runtime: '106 min',
    Title: 'The Graduate',
    Type: 'movie'
  },
  {
    Actors: 'Marlon Brando, Karl Malden, Lee J. Cobb, Rod Steiger',
    Awards: 'Won 8 Oscars. Another 21 wins & 9 nominations.',
    Director: 'Elia Kazan',
    Genre: 'Crime, Drama, Thriller',
    imdbID: 'tt0047296',
    imdbRating: '8.1/10',
    MetacriticRating: '91/100',
    Plot: 'An ex-prize fighter turned longshoreman struggles to stand up to his corrupt union bosses.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BY2I0MWFiZDMtNWQyYy00Njk5LTk3MDktZjZjNTNmZmVkYjkxXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '22 Jun 1954',
    RottenTomRating: '99%',
    Runtime: '108 min',
    Title: 'On the Waterfront',
    Type: 'movie'
  },
  {
    Actors: 'Liam Neeson, Ben Kingsley, Ralph Fiennes, Caroline Goodall',
    Awards: 'Won 7 Oscars. Another 84 wins & 49 nominations.',
    Director: 'Steven Spielberg',
    Genre: 'Biography, Drama, History',
    imdbID: 'tt0108052',
    imdbRating: '8.9/10',
    MetacriticRating: '94/100',
    Plot: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Rated: 'R',
    Released: '04 Feb 1994',
    RottenTomRating: '97%',
    Runtime: '195 min',
    Title: "Schindler's List",
    Type: 'movie'
  },
  {
    Actors: 'James Stewart, Donna Reed, Lionel Barrymore, Thomas Mitchell',
    Awards: 'Nominated for 5 Oscars. Another 6 wins & 1 nomination.',
    Director: 'Frank Capra',
    Genre: 'Drama, Family, Fantasy',
    imdbID: 'tt0038650',
    imdbRating: '8.6/10',
    MetacriticRating: '89/100',
    Plot: 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGdeQXVyNjUwMzI2NzU@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '07 Jan 1947',
    RottenTomRating: '94%',
    Runtime: '130 min',
    Title: "It's a Wonderful Life",
    Type: 'movie'
  },
  {
    Actors: 'William Holden, Alec Guinness, Jack Hawkins, Sessue Hayakawa',
    Awards: 'Won 7 Oscars. Another 23 wins & 8 nominations.',
    Director: 'David Lean',
    Genre: 'Adventure, Drama, War',
    imdbID: 'tt0050212',
    imdbRating: '8.1/10',
    MetacriticRating: '87/100',
    Plot: 'British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors, not knowing that the allied forces are planning to destroy it.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMGVhNjhjODktODgxYS00MDdhLTlkZjktYTkyNzQxMTU0ZDYxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '14 Dec 1957',
    RottenTomRating: '95%',
    Runtime: '161 min',
    Title: 'The Bridge on the River Kwai',
    Type: 'movie'
  },
  {
    Actors: 'Marilyn Monroe, Tony Curtis, Jack Lemmon, George Raft',
    Awards: 'Won 1 Oscar. Another 14 wins & 15 nominations.',
    Director: 'Billy Wilder',
    Genre: 'Comedy, Music, Romance',
    imdbID: 'tt0053291',
    imdbRating: '8.2/10',
    MetacriticRating: '98/100',
    Plot: 'After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzAyOGIxYjAtMGY2NC00ZTgyLWIwMWEtYzY0OWQ4NDFjOTc5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '19 Mar 1959',
    RottenTomRating: '95%',
    Runtime: '121 min',
    Title: 'Some Like It Hot',
    Type: 'movie'
  },
  {
    Actors: 'Bette Davis, Anne Baxter, George Sanders, Celeste Holm',
    Awards: 'Won 6 Oscars. Another 20 wins & 18 nominations.',
    Director: 'Joseph L. Mankiewicz',
    Genre: 'Drama',
    imdbID: 'tt0042192',
    imdbRating: '8.2/10',
    MetacriticRating: '98/100',
    Plot: 'A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY2MTAzODI5NV5BMl5BanBnXkFtZTgwMjM4NzQ0MjE@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '27 Oct 1950',
    RottenTomRating: '99%',
    Runtime: '138 min',
    Title: 'All About Eve',
    Type: 'movie'
  },
  {
    Actors: 'Humphrey Bogart, Katharine Hepburn, Robert Morley, Peter Bull',
    Awards: 'Won 1 Oscar. Another 3 wins & 8 nominations.',
    Director: 'John Huston',
    Genre: 'Adventure, Drama, Romance, War',
    imdbID: 'tt0043265',
    imdbRating: '7.7/10',
    MetacriticRating: '91/100',
    Plot: 'In WWI Africa, a gin-swilling riverboat captain is persuaded by a strait-laced missionary to use his boat to attack an enemy warship.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzM3YjE2NGMtODY3Zi00NTY0LWE4Y2EtMTE5YzNmM2U1NTg2XkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '21 Mar 1952',
    RottenTomRating: '98%',
    Runtime: '105 min',
    Title: 'The African Queen',
    Type: 'movie'
  },
  {
    Actors: 'Anthony Perkins, Vera Miles, John Gavin, Janet Leigh',
    Awards: 'Nominated for 4 Oscars. Another 7 wins & 10 nominations.',
    Director: 'Alfred Hitchcock',
    Genre: 'Horror, Mystery, Thriller',
    imdbID: 'tt0054215',
    imdbRating: '8.5/10',
    MetacriticRating: '97/100',
    Plot: "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BNTQwNDM1YzItNDAxZC00NWY2LTk0M2UtNDIwNWI5OGUyNWUxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '08 Sep 1960',
    RottenTomRating: '96%',
    Runtime: '109 min',
    Title: 'Psycho',
    Type: 'movie'
  },
  {
    Actors: 'Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez',
    Awards: 'Won 1 Oscar. Another 20 wins & 24 nominations.',
    Director: 'Roman Polanski',
    Genre: 'Drama, Mystery, Thriller',
    imdbID: 'tt0071315',
    imdbRating: '8.1/10',
    MetacriticRating: '92/100',
    Plot: 'A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOGMwYmY5ZmEtMzY1Yi00OWJiLTk1Y2MtMzI2MjBhYmZkNTQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '20 Jun 1974',
    RottenTomRating: '99%',
    Runtime: '130 min',
    Title: 'Chinatown',
    Type: 'movie'
  },
  {
    Actors: 'Michael Berryman, Peter Brocco, Dean R. Brooks, Alonzo Brown',
    Awards: 'Won 5 Oscars. Another 32 wins & 15 nominations.',
    Director: 'Milos Forman',
    Genre: 'Drama',
    imdbID: 'tt0073486',
    imdbRating: '8.7/10',
    MetacriticRating: '83/100',
    Plot: 'A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhOTAtYWQxNi00YzNhLWI4ZjYtNjFjZTEyYjJlNDVlL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Rated: 'R',
    Released: '19 Nov 1975',
    RottenTomRating: '94%',
    Runtime: '133 min',
    Title: "One Flew Over the Cuckoo's Nest",
    Type: 'movie'
  },
  {
    Actors: 'Henry Fonda, Jane Darwell, John Carradine, Charley Grapewin',
    Awards: 'Won 2 Oscars. Another 8 wins & 5 nominations.',
    Director: 'John Ford',
    Genre: 'Drama, History',
    imdbID: 'tt0032551',
    imdbRating: '8.0/10',
    MetacriticRating: '96/100',
    Plot: 'A poor Midwest family is forced off their land. They travel to California, suffering the misfortunes of the homeless in the Great Depression.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzJiOGI2MjctYjUyMS00ZjkzLWE2ZmUtOTg4NTZkOTNhZDc1L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '15 Mar 1940',
    RottenTomRating: '100%',
    Runtime: '129 min',
    Title: 'The Grapes of Wrath',
    Type: 'movie'
  },
  {
    Actors: 'Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter',
    Awards: 'Won 1 Oscar. Another 15 wins & 11 nominations.',
    Director: 'Stanley Kubrick',
    Genre: 'Adventure, Sci-Fi',
    imdbID: 'tt0062622',
    imdbRating: '8.3/10',
    MetacriticRating: '84/100',
    Plot: 'After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer H.A.L. 9000.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'G',
    Released: '24 Jun 1970',
    RottenTomRating: '92%',
    Runtime: '149 min',
    Title: '2001: A Space Odyssey',
    Type: 'movie'
  },
  {
    Actors: 'Humphrey Bogart, Mary Astor, Gladys George, Peter Lorre',
    Awards: 'Nominated for 3 Oscars. Another 5 wins.',
    Director: 'John Huston',
    Genre: 'Crime, Film-Noir, Mystery, Romance',
    imdbID: 'tt0033870',
    imdbRating: '8.0/10',
    MetacriticRating: '96/100',
    Plot: 'A private detective takes on a case that involves him with three eccentric criminals, a gorgeous liar, and their quest for a priceless statuette.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZjIwNGM1ZTUtOThjYS00NDdiLTk2ZDYtNGY5YjJkNzliM2JjL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '18 Oct 1941',
    RottenTomRating: '100%',
    Runtime: '100 min',
    Title: 'The Maltese Falcon',
    Type: 'movie'
  },
  {
    Actors: 'Robert De Niro, Cathy Moriarty, Joe Pesci, Frank Vincent',
    Awards: 'Won 2 Oscars. Another 22 wins & 28 nominations.',
    Director: 'Martin Scorsese',
    Genre: 'Biography, Drama, Sport',
    imdbID: 'tt0081398',
    imdbRating: '8.2/10',
    MetacriticRating: '89/100',
    Plot: 'The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjRmODkzNDItMTNhNi00YjJlLTg0ZjAtODlhZTM0YzgzYThlXkEyXkFqcGdeQXVyNzQ1ODk3MTQ@._V1_SX300.jpg',
    Rated: 'R',
    Released: '19 Dec 1980',
    RottenTomRating: '93%',
    Runtime: '129 min',
    Title: 'Raging Bull',
    Type: 'movie'
  },
  {
    Actors: 'Dee Wallace, Henry Thomas, Peter Coyote, Robert MacNaughton',
    Awards: 'Won 4 Oscars. Another 48 wins & 36 nominations.',
    Director: 'Steven Spielberg',
    Genre: 'Family, Sci-Fi',
    imdbID: 'tt0083866',
    imdbRating: '7.8/10',
    MetacriticRating: '91/100',
    Plot: 'A troubled child summons the courage to help a friendly alien escape Earth and return to his home world.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTQ2ODFlMDAtNzdhOC00ZDYzLWE3YTMtNDU4ZGFmZmJmYTczXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '11 Jun 1982',
    RottenTomRating: '98%',
    Runtime: '115 min',
    Title: 'E.T. the Extra-Terrestrial',
    Type: 'movie'
  },
  {
    Actors: 'Peter Sellers, George C. Scott, Sterling Hayden, Keenan Wynn',
    Awards: 'Nominated for 4 Oscars. Another 14 wins & 7 nominations.',
    Director: 'Stanley Kubrick',
    Genre: 'Comedy',
    imdbID: 'tt0057012',
    imdbRating: '8.4/10',
    MetacriticRating: '97/100',
    Plot: 'An insane general triggers a path to nuclear holocaust that a War Room full of politicians and generals frantically tries to stop.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZWI3ZTMxNjctMjdlNS00NmUwLWFiM2YtZDUyY2I3N2MxYTE0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '29 Jan 1964',
    RottenTomRating: '98%',
    Runtime: '95 min',
    Title: 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
    Type: 'movie'
  },
  {
    Actors: 'Warren Beatty, Faye Dunaway, Michael J. Pollard, Gene Hackman',
    Awards: 'Won 2 Oscars. Another 21 wins & 30 nominations.',
    Director: 'Arthur Penn',
    Genre: 'Action, Biography, Crime, Drama',
    imdbID: 'tt0061418',
    imdbRating: '7.8/10',
    MetacriticRating: '86/100',
    Plot: 'Bored waitress Bonnie Parker falls in love with an ex-con named Clyde Barrow and together they start a violent crime spree through the country, stealing cars and robbing banks.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTViZmMwOGEtYzc4Yy00ZGQ1LWFkZDQtMDljNGZlMjAxMjhiXkEyXkFqcGdeQXVyNzM0MTUwNTY@._V1_SX300.jpg',
    Rated: 'R',
    Released: '14 Aug 1967',
    RottenTomRating: '88%',
    Runtime: '111 min',
    Title: 'Bonnie and Clyde',
    Type: 'movie'
  },
  {
    Actors: 'Marlon Brando, Martin Sheen, Robert Duvall, Frederic Forrest',
    Awards: 'Won 2 Oscars. Another 19 wins & 32 nominations.',
    Director: 'Francis Ford Coppola',
    Genre: 'Drama, Mystery, War',
    imdbID: 'tt0078788',
    imdbRating: '8.4/10',
    MetacriticRating: '94/100',
    Plot: 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '15 Aug 1979',
    RottenTomRating: '98%',
    Runtime: '147 min',
    Title: 'Apocalypse Now',
    Type: 'movie'
  },
  {
    Actors: 'Jean Arthur, James Stewart, Claude Rains, Edward Arnold',
    Awards: 'Won 1 Oscar. Another 5 wins & 16 nominations.',
    Director: 'Frank Capra',
    Genre: 'Comedy, Drama',
    imdbID: 'tt0031679',
    imdbRating: '8.1/10',
    MetacriticRating: '73/100',
    Plot: "A naive man is appointed to fill a vacancy in the United States Senate. His plans promptly collide with political corruption, but he doesn't back down.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BZTYwYjYxYzgtMDE1Ni00NzU4LWJlMTEtODQ5YmJmMGJhZjI5L2ltYWdlXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '19 Oct 1939',
    RottenTomRating: '85%',
    Runtime: '129 min',
    Title: 'Mr. Smith Goes to Washington',
    Type: 'movie'
  },
  {
    Actors: 'Humphrey Bogart, Walter Huston, Tim Holt, Bruce Bennett',
    Awards: 'Won 3 Oscars. Another 13 wins & 8 nominations.',
    Director: 'John Huston',
    Genre: 'Adventure, Drama, Western',
    imdbID: 'tt0040897',
    imdbRating: '8.2/10',
    MetacriticRating: '98/100',
    Plot: 'Two Americans searching for work in Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTJlZWMxYzEtMjlkMS00ODE0LThlM2ItMDI3NGQ2YjhmMzkxXkEyXkFqcGdeQXVyMDI2NDg0NQ@@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '24 Jan 1948',
    RottenTomRating: '93%',
    Runtime: '126 min',
    Title: 'The Treasure of the Sierra Madre',
    Type: 'movie'
  },
  {
    Actors: 'Woody Allen, Diane Keaton, Tony Roberts, Carol Kane',
    Awards: 'Won 4 Oscars. Another 27 wins & 8 nominations.',
    Director: 'Woody Allen',
    Genre: 'Comedy, Romance',
    imdbID: 'tt0075686',
    imdbRating: '8.0/10',
    MetacriticRating: '92/100',
    Plot: 'Alvy Singer, a divorced Jewish comedian, reflects on his relationship with ex-lover Annie Hall, an aspiring nightclub singer, which ended abruptly just like his previous marriages.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BZDg1OGQ4YzgtM2Y2NS00NjA3LWFjYTctMDRlMDI3NWE1OTUyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '20 Apr 1977',
    RottenTomRating: '98%',
    Runtime: '93 min',
    Title: 'Annie Hall',
    Type: 'movie'
  },
  {
    Actors: 'Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro',
    Awards: 'Won 6 Oscars. Another 11 wins & 20 nominations.',
    Director: 'Francis Ford Coppola',
    Genre: 'Crime, Drama',
    imdbID: 'tt0071562',
    imdbRating: '9.0/10',
    MetacriticRating: '90/100',
    Plot: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '18 Dec 1974',
    RottenTomRating: '98%',
    Runtime: '202 min',
    Title: 'The Godfather: Part II',
    Type: 'movie'
  },
  {
    Actors: 'Gary Cooper, Thomas Mitchell, Lloyd Bridges, Katy Jurado',
    Awards: 'Won 4 Oscars. Another 13 wins & 10 nominations.',
    Director: 'Fred Zinnemann',
    Genre: 'Drama, Thriller, Western',
    imdbID: 'tt0044706',
    imdbRating: '7.9/10',
    MetacriticRating: '89/100',
    Plot: 'A town Marshal, despite the disagreements of his newlywed bride and the townspeople around him, must face a gang of deadly killers alone at high noon when the gang leader, an outlaw he sent up years ago, arrives on the noon train.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOWIzZGUxZmItOThkMS00Y2QxLTg0MTYtMDdhMjRlNTNlYTI3L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '30 Jul 1952',
    RottenTomRating: '97%',
    Runtime: '85 min',
    Title: 'High Noon',
    Type: 'movie'
  },
  {
    Actors: 'Gregory Peck, John Megna, Frank Overton, Rosemary Murphy',
    Awards: 'Won 3 Oscars. Another 10 wins & 16 nominations.',
    Director: 'Robert Mulligan',
    Genre: 'Crime, Drama',
    imdbID: 'tt0056592',
    imdbRating: '8.2/10',
    MetacriticRating: '88/100',
    Plot: 'Atticus Finch, a lawyer in the Depression-era South, defends a black man against an undeserved rape charge, and his children against prejudice.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNmVmYzcwNzMtMWM1NS00MWIyLThlMDEtYzUwZDgzODE1NmE2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '16 Mar 1963',
    RottenTomRating: '92%',
    Runtime: '129 min',
    Title: 'To Kill a Mockingbird',
    Type: 'movie'
  },
  {
    Actors: 'Clark Gable, Claudette Colbert, Walter Connolly, Roscoe Karns',
    Awards: 'Won 5 Oscars. Another 6 wins & 2 nominations.',
    Director: 'Frank Capra',
    Genre: 'Comedy, Romance',
    imdbID: 'tt0025316',
    imdbRating: '8.1/10',
    MetacriticRating: '87/100',
    Plot: 'A renegade reporter and a crazy young heiress meet on a bus heading for New York, and end up stuck with each other when the bus leaves them behind at one of the stops.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BYzJmMWE5NjAtNWMyZS00NmFiLWIwMDgtZDE2NzczYWFhNzIzXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '22 Feb 1934',
    RottenTomRating: '98%',
    Runtime: '105 min',
    Title: 'It Happened One Night',
    Type: 'movie'
  },
  {
    Actors: 'Dustin Hoffman, Jon Voight, Sylvia Miles, John McGiver',
    Awards: 'Won 3 Oscars. Another 25 wins & 16 nominations.',
    Director: 'John Schlesinger',
    Genre: 'Drama',
    imdbID: 'tt0064665',
    imdbRating: '7.8/10',
    MetacriticRating: '79/100',
    Plot: 'A naive hustler travels from Texas to New York City to seek personal fortune, finding a new friend in the process.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNTgwZmIzMmYtZjE3Yy00NzgzLTgxNmUtNjlmZDlkMzlhOTJkXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg',
    Rated: 'R',
    Released: '25 May 1969',
    RottenTomRating: '88%',
    Runtime: '113 min',
    Title: 'Midnight Cowboy',
    Type: 'movie'
  },
  {
    Actors: 'Myrna Loy, Fredric March, Dana Andrews, Teresa Wright',
    Awards: 'Won 7 Oscars. Another 14 wins & 3 nominations.',
    Director: 'William Wyler',
    Genre: 'Drama, Romance, War',
    imdbID: 'tt0036868',
    imdbRating: '8.0/10',
    MetacriticRating: '93/100',
    Plot: 'Three World War II veterans return home to small-town America to discover that they and their families have been irreparably changed.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BY2RmNTRjYzctODI4Ni00MzQyLWEyNTAtNjU0N2JkMTNhNjJkXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '29 May 1947',
    RottenTomRating: '97%',
    Runtime: '170 min',
    Title: 'The Best Years of Our Lives',
    Type: 'movie'
  },
  {
    Actors: 'Fred MacMurray, Barbara Stanwyck, Edward G. Robinson, Porter Hall',
    Awards: 'Nominated for 7 Oscars. Another 2 wins & 2 nominations.',
    Director: 'Billy Wilder',
    Genre: 'Crime, Drama, Film-Noir, Mystery, Thriller',
    imdbID: 'tt0036775',
    imdbRating: '8.3/10',
    MetacriticRating: '95/100',
    Plot: 'An insurance representative lets himself be talked by a seductive housewife into a murder/insurance fraud scheme that arouses the suspicion of an insurance investigator.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BOTdlNjgyZGUtOTczYi00MDdhLTljZmMtYTEwZmRiOWFkYjRhXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '06 Jul 1944',
    RottenTomRating: '97%',
    Runtime: '107 min',
    Title: 'Double Indemnity',
    Type: 'movie'
  },
  {
    Actors: 'Omar Sharif, Julie Christie, Geraldine Chaplin, Rod Steiger',
    Awards: 'Won 5 Oscars. Another 16 wins & 13 nominations.',
    Director: 'David Lean',
    Genre: 'Drama, Romance, War',
    imdbID: 'tt0059113',
    imdbRating: '8.0/10',
    MetacriticRating: '69/100',
    Plot: "The life of a Russian physician and poet who, although married to another, falls in love with a political activist's wife and experiences hardship during World War I and then the October Revolution.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzdmZTk4MTktZmExNi00OWEwLTgxZDctNTE4NWMwNjc1Nzg2XkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
    Rated: 'PG-13',
    Released: '31 Dec 1965',
    RottenTomRating: '84%',
    Runtime: '197 min',
    Title: 'Doctor Zhivago',
    Type: 'movie'
  },
  {
    Actors: 'Natalie Wood, Richard Beymer, Russ Tamblyn, Rita Moreno',
    Awards: 'Won 10 Oscars. Another 18 wins & 10 nominations.',
    Director: 'Jerome Robbins, Robert Wise',
    Genre: 'Crime, Drama, Musical, Romance',
    imdbID: 'tt0055614',
    imdbRating: '7.5/10',
    MetacriticRating: '86/100',
    Plot: 'Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTM0NDAxOTI5MF5BMl5BanBnXkFtZTcwNjI4Mjg3NA@@._V1_SX300.jpg',
    Rated: 'Approved',
    Released: '18 Oct 1961',
    RottenTomRating: '92%',
    Runtime: '153 min',
    Title: 'West Side Story',
    Type: 'movie'
  },
  {
    Actors: 'James Stewart, Grace Kelly, Wendell Corey, Thelma Ritter',
    Awards: 'Nominated for 4 Oscars. Another 6 wins & 9 nominations.',
    Director: 'Alfred Hitchcock',
    Genre: 'Mystery, Thriller',
    imdbID: 'tt0047396',
    imdbRating: '8.4/10',
    MetacriticRating: '100/100',
    Plot: 'A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '01 Sep 1954',
    RottenTomRating: '97%',
    Runtime: '112 min',
    Title: 'Rear Window',
    Type: 'movie'
  },
  {
    Actors: 'Naomi Watts, Jack Black, Adrien Brody, Thomas Kretschmann',
    Awards: 'Won 3 Oscars. Another 43 wins & 104 nominations.',
    Director: 'Peter Jackson',
    Genre: 'Action, Adventure, Drama, Romance',
    imdbID: 'tt0360717',
    imdbRating: '7.2/10',
    MetacriticRating: '81/100',
    Plot: 'A greedy film producer assembles a team of moviemakers and sets out for the infamous Skull Island, where they find more than just cannibalistic natives.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMjYxYmRlZWYtMzAwNC00MDA1LWJjNTItOTBjMzlhNGMzYzk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg',
    Rated: 'PG-13',
    Released: '14 Dec 2005',
    RottenTomRating: '84%',
    Runtime: '187 min',
    Title: 'King Kong',
    Type: 'movie'
  },
  {
    Actors: 'Nate Parker, Armie Hammer, Penelope Ann Miller, Jackie Earle Haley',
    Awards: '3 wins & 29 nominations.',
    Director: 'Nate Parker',
    Genre: 'Biography, Drama, History',
    imdbID: 'tt4196450',
    imdbRating: '6.4/10',
    MetacriticRating: '69/100',
    Plot: 'Nat Turner, a literate slave and preacher in the antebellum South, orchestrates an uprising.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTU5MjI3NzQxMl5BMl5BanBnXkFtZTgwMTUwNjYyOTE@._V1_SX300.jpg',
    Rated: 'R',
    Released: '07 Oct 2016',
    RottenTomRating: '73%',
    Runtime: '120 min',
    Title: 'The Birth of a Nation',
    Type: 'movie'
  },
  {
    Actors: 'Vivien Leigh, Marlon Brando, Kim Hunter, Karl Malden',
    Awards: 'Won 4 Oscars. Another 13 wins & 15 nominations.',
    Director: 'Elia Kazan',
    Genre: 'Drama',
    imdbID: 'tt0044081',
    imdbRating: '8.0/10',
    MetacriticRating: '97/100',
    Plot: 'Disturbed Blanche DuBois moves in with her sister in New Orleans and is tormented by her brutish brother-in-law while her reality crumbles around her.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BNzk2M2Y3MzYtNGMzMi00Y2FjLTkwODQtNmExYWU3ZWY3NzExXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '01 Dec 1951',
    RottenTomRating: '98%',
    Runtime: '122 min',
    Title: 'A Streetcar Named Desire',
    Type: 'movie'
  },
  {
    Actors: 'Malcolm McDowell, Patrick Magee, Michael Bates, Warren Clarke',
    Awards: 'Nominated for 4 Oscars. Another 12 wins & 20 nominations.',
    Director: 'Stanley Kubrick',
    Genre: 'Crime, Drama, Sci-Fi',
    imdbID: 'tt0066921',
    imdbRating: '8.3/10',
    MetacriticRating: '77/100',
    Plot: "In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTY3MjM1Mzc4N15BMl5BanBnXkFtZTgwODM0NzAxMDE@._V1_SX300.jpg',
    Rated: 'R',
    Released: '02 Feb 1972',
    RottenTomRating: '86%',
    Runtime: '136 min',
    Title: 'A Clockwork Orange',
    Type: 'movie'
  },
  {
    Actors: 'Diahnne Abbott, Frank Adu, Victor Argo, Gino Ardito',
    Awards: 'Nominated for 4 Oscars. Another 22 wins & 16 nominations.',
    Director: 'Martin Scorsese',
    Genre: 'Crime, Drama',
    imdbID: 'tt0075314',
    imdbRating: '8.2/10',
    MetacriticRating: '94/100',
    Plot: 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action by attempting to liberate a presidential campaign worker and an underage prostitute.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BM2M1MmVhNDgtNmI0YS00ZDNmLTkyNjctNTJiYTQ2N2NmYzc2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg',
    Rated: 'R',
    Released: '09 Feb 1976',
    RottenTomRating: '96%',
    Runtime: '114 min',
    Title: 'Taxi Driver',
    Type: 'movie'
  },
  {
    Actors: 'Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary',
    Awards: 'Won 3 Oscars. Another 12 wins & 20 nominations.',
    Director: 'Steven Spielberg',
    Genre: 'Adventure, Thriller',
    imdbID: 'tt0073195',
    imdbRating: '8.0/10',
    MetacriticRating: '87/100',
    Plot: "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '20 Jun 1975',
    RottenTomRating: '98%',
    Runtime: '124 min',
    Title: 'Jaws',
    Type: 'movie'
  },
  {
    Actors: 'Paul Newman, Robert Redford, Katharine Ross, Strother Martin',
    Awards: 'Won 4 Oscars. Another 17 wins & 15 nominations.',
    Director: 'George Roy Hill',
    Genre: 'Biography, Crime, Drama, Western',
    imdbID: 'tt0064115',
    imdbRating: '8.0/10',
    MetacriticRating: '66/100',
    Plot: 'Wyoming, early 1900s. Butch Cassidy and The Sundance Kid are the leaders of a band of outlaws. After a train robbery goes wrong they find themselves on the run with a posse hard on their heels. Their solution - escape to Bolivia.',
    Poster: 'https://m.media-amazon.com/images/M/MV5BMTkyMTM2NDk5Nl5BMl5BanBnXkFtZTgwNzY1NzEyMDE@._V1_SX300.jpg',
    Rated: 'PG',
    Released: '24 Sep 1969',
    RottenTomRating: '90%',
    Runtime: '110 min',
    Title: 'Butch Cassidy and the Sundance Kid',
    Type: 'movie'
  },
  {
    Actors: 'Cary Grant, Katharine Hepburn, James Stewart, Ruth Hussey',
    Awards: 'Won 2 Oscars. Another 3 wins & 5 nominations.',
    Director: 'George Cukor',
    Genre: 'Comedy, Romance',
    imdbID: 'tt0032904',
    imdbRating: '7.9/10',
    MetacriticRating: '96/100',
    Plot: "When a rich woman's ex-husband and a tabloid-type reporter turn up just before her planned remarriage, she begins to learn the truth about herself.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BYjQ4ZDA4NGMtMTkwYi00NThiLThhZDUtZTEzNTAxOWYyY2E4XkEyXkFqcGdeQXVyMjUxODE0MDY@._V1_SX300.jpg',
    Rated: 'Not Rated',
    Released: '17 Jan 1941',
    RottenTomRating: '93%',
    Runtime: '112 min',
    Title: 'The Philadelphia Story',
    Type: 'movie'
  },
  {
    Actors: 'Burt Lancaster, Montgomery Clift, Deborah Kerr, Donna Reed',
    Awards: 'Won 8 Oscars. Another 17 wins & 7 nominations.',
    Director: 'Fred Zinnemann',
    Genre: 'Drama, Romance, War',
    imdbID: 'tt0045793',
    imdbRating: '7.6/10',
    MetacriticRating: '85/100',
    Plot: "In Hawaii in 1941, a private is cruelly punished for not boxing on his unit's team, while his captain's wife and second-in-command are falling in love.",
    Poster: 'https://m.media-amazon.com/images/M/MV5BM2U3YzkxNGMtYWE0YS00ODk0LTk1ZGEtNjk3ZTE0MTk4MzJjXkEyXkFqcGdeQXVyNDk0MDg4NDk@._V1_SX300.jpg',
    Rated: 'Passed',
    Released: '28 Aug 1953',
    RottenTomRating: '92%',
    Runtime: '118 min',
    Title: 'From Here to Eternity',
    Type: 'movie'
  }
]
const seedMovies = () => Movie.bulkCreate(movieData);

module.exports = seedMovies;